# Docker Compose для использования с готовыми образами из Docker Hub

services:
  server:
    image: webusov/satellite-server:latest
    container_name: satellite-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - N2YO_API_KEY=${N2YO_API_KEY}
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - satellite-network

  client:
    image: webusov/satellite-client:latest
    container_name: satellite-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - satellite-network

networks:
  satellite-network:
    driver: bridge

