version: '3.8'

services:
  server:
    image: webusov/satellite-server:latest
    container_name: satellite-server
    restart: unless-stopped
    environment:
      - N2YO_API_KEY=${N2YO_API_KEY}
      - PORT=3001
    ports:
      - "3001:3001"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  client:
    image: webusov/satellite-client:latest
    container_name: satellite-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL:-}
    command: --interval 300 --cleanup

networks:
  default:
    name: satellite-network

